"""initial medlink schema

Revision ID: 31229f2c3123
Revises: 
Create Date: 2026-09-10 04:36:16.797192

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31229f2c3123'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_ts', 'audit_log', ['ts'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('phone_enc', sa.LargeBinary(), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('on_call', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_enc', sa.LargeBinary(), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_store', sa.Boolean(), nullable=False),
    sa.Column('consent_share_doctor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('triage_entry_id', sa.String(length=64), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('disposition', sa.String(length=32), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_session_id'), 'calls', ['session_id'], unique=True)
    op.create_index('ix_calls_started_at', 'calls', ['started_at'], unique=False)
    op.create_index(op.f('ix_calls_user_id'), 'calls', ['user_id'], unique=False)
    op.create_table('call_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_answers_call_id'), 'call_answers', ['call_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('call_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('consent_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_call_id'), 'escalations', ['call_id'], unique=False)
    op.create_table('medicine_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('formulary_id', sa.String(length=64), nullable=False),
    sa.Column('generic_name', sa.String(length=128), nullable=False),
    sa.Column('dose_text', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_recommendations_call_id'), 'medicine_recommendations', ['call_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('text_en_gloss', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_call_id'), 'messages', ['call_id'], unique=False)
    op.create_table('triage_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('triage_entry_id', sa.String(length=64), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('red_flag_category', sa.String(length=64), nullable=True),
    sa.Column('red_flag_term', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_assessments_call_id'), 'triage_assessments', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_assessments_call_id'), table_name='triage_assessments')
    op.drop_table('triage_assessments')
    op.drop_index(op.f('ix_messages_call_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_medicine_recommendations_call_id'), table_name='medicine_recommendations')
    op.drop_table('medicine_recommendations')
    op.drop_index(op.f('ix_escalations_call_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_table('consents')
    op.drop_index(op.f('ix_call_answers_call_id'), table_name='call_answers')
    op.drop_table('call_answers')
    op.drop_index(op.f('ix_calls_user_id'), table_name='calls')
    op.drop_index('ix_calls_started_at', table_name='calls')
    op.drop_index(op.f('ix_calls_session_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_table('users')
    op.drop_table('providers')
    op.drop_index('ix_audit_ts', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
