"""add patient demographics, symptoms, medical history, medication source

Revision ID: cdef9d05e7cf
Revises: 31229f2c3123
Create Date: 2026-09-10 20:09:47.253072

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cdef9d05e7cf'
down_revision: str | Sequence[str] | None = '31229f2c3123'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_call_id'), 'medical_history', ['call_id'], unique=False)
    op.create_index(op.f('ix_medical_history_user_id'), 'medical_history', ['user_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('formulary_id', sa.String(length=64), nullable=True),
    sa.Column('generic_name', sa.String(length=128), nullable=False),
    sa.Column('dose_text', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=128), nullable=True),
    sa.Column('duration_text', sa.String(length=128), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_call_id'), 'medications', ['call_id'], unique=False)
    op.create_index(op.f('ix_medications_source'), 'medications', ['source'], unique=False)
    op.create_index(op.f('ix_medications_user_id'), 'medications', ['user_id'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('symptom', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('onset', sa.String(length=64), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptoms_call_id'), 'symptoms', ['call_id'], unique=False)
    op.create_index(op.f('ix_symptoms_user_id'), 'symptoms', ['user_id'], unique=False)
    # `medicine_recommendations` becomes `medications`, which now also holds
    # medicines the caller reports and ones a doctor prescribed. Every existing
    # row was written by the agent, so it migrates as 'ai_recommended'.
    op.execute(
        """
        INSERT INTO medications (
            id, call_id, user_id, source, formulary_id,
            generic_name, dose_text, details, created_at
        )
        SELECT id, call_id, NULL, 'ai_recommended', formulary_id,
               generic_name, dose_text, details, created_at
        FROM medicine_recommendations
        """
    )
    op.drop_index(op.f('ix_medicine_recommendations_call_id'), table_name='medicine_recommendations')
    op.drop_table('medicine_recommendations')
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('age_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age_years')
    op.drop_column('users', 'name')
    op.create_table('medicine_recommendations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('formulary_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('generic_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('dose_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('medicine_recommendations_call_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medicine_recommendations_pkey'))
    )
    op.create_index(op.f('ix_medicine_recommendations_call_id'), 'medicine_recommendations', ['call_id'], unique=False)
    # Only AI recommendations existed in the old table; anything patient-reported
    # or doctor-prescribed has no home there and is intentionally dropped.
    op.execute(
        """
        INSERT INTO medicine_recommendations (
            id, call_id, formulary_id, generic_name, dose_text, details, created_at
        )
        SELECT id, call_id, COALESCE(formulary_id, 'unknown'),
               generic_name, dose_text, details, created_at
        FROM medications
        WHERE source = 'ai_recommended'
        """
    )
    op.drop_index(op.f('ix_symptoms_user_id'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_call_id'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_medications_user_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_source'), table_name='medications')
    op.drop_index(op.f('ix_medications_call_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_history_user_id'), table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_call_id'), table_name='medical_history')
    op.drop_table('medical_history')
    # ### end Alembic commands ###
